In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [25]:
# data input
main = pd.read_csv('main.csv', sep = ';', index_col = 'cust_id')
cust = pd.read_csv('cust.csv', sep = ';', index_col = 'cust_id')

In [26]:
main.head()

,model1,model2,boughtItemsTotal,itemOneTotal,itemTwoTotal,itemThreeTotal,Visits2014,itemOneTotal2014,itemTwoTotal2014,itemThreeTotal2014,...,numVisitsL3M,numVisitsL6M,numVisits_trendL3M,fractionItemOneL1M,fractionItemOneTwoThreeL1M,fractionItemOneL3M,fractionItemOneTwoThreeL3M,fractionItemOneL6M,fractionItemOneTwoThreeL6M,numItemOne_trendL3M
cust_id,,,,,,,,,,,,,,,,,,,,,
0,3,190,24,7,4,2,4,2,0,0,...,4,8,1.000000,0.0,0.0,0.500000,0.50,0.375000,0.500000,1.333333
1,1,280,49,12,5,8,2,1,1,0,...,2,7,0.400000,1.0,1.0,0.500000,1.00,0.285714,0.714286,1.750000
2,2,254,27,6,6,1,5,1,1,0,...,4,10,0.666667,0.0,0.5,0.000000,0.25,0.200000,0.600000,0.000000
3,0,464,43,12,6,3,7,1,1,1,...,6,10,1.500000,0.0,0.0,0.166667,0.50,0.100000,0.300000,1.666667
4,6,116,28,11,5,2,7,2,1,1,...,6,7,6.000000,0.5,0.5,0.333333,0.50,0.285714,0.571429,1.166667

In [27]:
cust.head()

                              pref  score
cust_id
0        preferenceItemOneTwoThree  48.15
0                preferenceItemOne  25.93
1        preferenceItemOneTwoThree  50.98
1                preferenceItemOne  23.53
2        preferenceItemOneTwoThree  41.18

In [32]:
cust_new = cust.pivot_table(index = 'cust_id', columns = 'pref')

In [33]:
pd.merge(main, cust_new)

C:\Users\c.luo\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\reshape\merge.py:558: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

MergeError: No common columns to perform merge on

In [24]:
main.pivot_table(index='boughtItem')

,Visits2013,Visits2014,boughtItemsTotal,date_lastVisit,daysSinceVisit,fractionItemOneL1M,fractionItemOneL3M,fractionItemOneL6M,fractionItemOneTwoThreeL1M,fractionItemOneTwoThreeL3M,...,itemTwoTotal,itemTwoTotal2013,itemTwoTotal2014,model1,model2,numItemOne_trendL3M,numVisitsL1M,numVisitsL3M,numVisitsL6M,numVisits_trendL3M
boughtItem,,,,,,,,,,,,,,,,,,,,,
0,11.572395,8.740189,39.129905,140709.274696,19.690122,0.148850,0.164303,0.171678,0.391069,0.414301,...,5.181326,1.434371,1.190798,5.372124,393.972936,0.667804,1.322057,4.433018,8.105548,1.258058
1,9.747059,8.041176,30.141176,140737.676471,19.111765,0.344118,0.312787,0.291870,0.537255,0.574132,...,4.635294,1.382353,1.370588,22.811765,86.917647,0.885724,1.282353,4.158824,7.741176,1.129531
2,9.715976,8.053254,30.982249,140689.408284,17.899408,0.234714,0.231819,0.225384,0.527613,0.532079,...,4.763314,1.372781,1.390533,14.532544,147.142012,0.808155,1.414201,4.491124,7.443787,1.486078
3,10.917722,8.594937,35.335443,140687.322785,18.911392,0.162447,0.210237,0.211211,0.479430,0.489763,...,5.120253,1.500000,1.208861,10.702532,202.341772,0.766336,1.335443,4.379747,7.626582,1.441795
4,10.083333,8.262821,32.737179,140728.224359,20.397436,0.182692,0.194292,0.199684,0.434829,0.428655,...,4.756410,1.423077,1.230769,7.666667,241.602564,0.737540,1.314103,4.237179,7.769231,1.342267
5,10.542484,8.797386,33.986928,140617.908497,23.196078,0.133442,0.192608,0.197030,0.434096,0.467242,...,4.901961,1.385621,1.379085,6.588235,287.843137,0.759199,1.359477,4.261438,7.986928,1.220293
6,10.608392,8.531469,34.223776,140681.020979,18.475524,0.195804,0.207925,0.205638,0.448718,0.453796,...,4.699301,1.419580,1.209790,6.398601,315.993007,0.795801,1.363636,4.510490,7.881119,1.337313
7,16.318182,9.409091,51.000000,140662.681818,17.727273,0.227273,0.148106,0.155271,0.500000,0.462879,...,6.409091,1.863636,1.681818,4.727273,399.045455,0.566136,1.545455,4.500000,9.000000,1.344426
8,3.000000,4.000000,7.000000,140523.000000,82.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,1.000000,2.000000,1.000000,718.000000,0.000000,0.000000,1.000000,4.000000,0.333333
d,9.697674,8.395349,31.193798,140743.976744,20.186047,0.143411,0.196712,0.224989,0.403101,0.439753,...,4.155039,1.294574,1.139535,8.519380,256.775194,0.670346,1.248062,4.054264,7.713178,1.189516